language: node_js
node_js:
  - "iojs"
  - "7"
install: npm install
test:
  override:
    - echo "no tests"
scripts:
  - ssh -v daniel13a@s9.mydevil.net << EOF
  - cd ./domains/slack.kamilantropik.pl/public_nodejs
  - git checkout --force master
  - EOF 